name: CreeperMarriage
main: vip.creeper.mcserverplugins.creepermarriage.Main
author: July_ss
version: 1.0.0
softdepend: [BossShop,PlaceholderAPI]
depend: [Vault,PlayerPoints,CreeperTitleApi]
commands:
  cmarry:
   aliases: [cm,marry]