name: CreeperMarriage
main: vip.creeper.mcserverplugins.creepermarriage.Main
author: July_ss
version: 1.0.0
softdepend: [PlaceholderAPI]
depend: [Vault,PlayerPoints,CreeperTitleAPI]
commands:
  ocmarry:
  cmarry:
   aliases: [marry]